/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  KnowledgeUnit,
  KnowledgeUnitRequest,
  KnowledgeUnitWithDocumentsResponse,
} from '../models/index';
import {
    KnowledgeUnitFromJSON,
    KnowledgeUnitToJSON,
    KnowledgeUnitRequestFromJSON,
    KnowledgeUnitRequestToJSON,
    KnowledgeUnitWithDocumentsResponseFromJSON,
    KnowledgeUnitWithDocumentsResponseToJSON,
} from '../models/index';

export interface KnowledgeUnitsIdDeleteRequest {
    id: string;
}

export interface KnowledgeUnitsIdGetRequest {
    id: string;
}

export interface KnowledgeUnitsIdPutRequest {
    id: string;
    knowledgeUnitRequest: KnowledgeUnitRequest;
}

export interface KnowledgeUnitsPostRequest {
    knowledgeUnitRequest: KnowledgeUnitRequest;
}

/**
 * 
 */
export class KnowledgeUnitResourceApi extends runtime.BaseAPI {

    /**
     * Get Knowledge Units
     */
    async knowledgeUnitsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KnowledgeUnit>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/knowledge-units`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KnowledgeUnitFromJSON));
    }

    /**
     * Get Knowledge Units
     */
    async knowledgeUnitsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KnowledgeUnit>> {
        const response = await this.knowledgeUnitsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete Knowledge Unit
     */
    async knowledgeUnitsIdDeleteRaw(requestParameters: KnowledgeUnitsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeUnitsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/knowledge-units/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Knowledge Unit
     */
    async knowledgeUnitsIdDelete(requestParameters: KnowledgeUnitsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeUnitsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Knowledge Unit With Documents
     */
    async knowledgeUnitsIdGetRaw(requestParameters: KnowledgeUnitsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KnowledgeUnitWithDocumentsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeUnitsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/knowledge-units/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KnowledgeUnitWithDocumentsResponseFromJSON(jsonValue));
    }

    /**
     * Get Knowledge Unit With Documents
     */
    async knowledgeUnitsIdGet(requestParameters: KnowledgeUnitsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KnowledgeUnitWithDocumentsResponse> {
        const response = await this.knowledgeUnitsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Knowledge Unit
     */
    async knowledgeUnitsIdPutRaw(requestParameters: KnowledgeUnitsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling knowledgeUnitsIdPut().'
            );
        }

        if (requestParameters['knowledgeUnitRequest'] == null) {
            throw new runtime.RequiredError(
                'knowledgeUnitRequest',
                'Required parameter "knowledgeUnitRequest" was null or undefined when calling knowledgeUnitsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/knowledge-units/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: KnowledgeUnitRequestToJSON(requestParameters['knowledgeUnitRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Knowledge Unit
     */
    async knowledgeUnitsIdPut(requestParameters: KnowledgeUnitsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeUnitsIdPutRaw(requestParameters, initOverrides);
    }

    /**
     * Create Knowledge Unit
     */
    async knowledgeUnitsPostRaw(requestParameters: KnowledgeUnitsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['knowledgeUnitRequest'] == null) {
            throw new runtime.RequiredError(
                'knowledgeUnitRequest',
                'Required parameter "knowledgeUnitRequest" was null or undefined when calling knowledgeUnitsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/knowledge-units`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KnowledgeUnitRequestToJSON(requestParameters['knowledgeUnitRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Knowledge Unit
     */
    async knowledgeUnitsPost(requestParameters: KnowledgeUnitsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.knowledgeUnitsPostRaw(requestParameters, initOverrides);
    }

}
