services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: knowledge-manager-postgres
    environment:
      POSTGRES_DB: knowledge_manager
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d knowledge_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: