/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JSONB
 */
export interface JSONB {
    /**
     * 
     * @type {string}
     * @memberof JSONB
     */
    data?: string;
}

/**
 * Check if a given object implements the JSONB interface.
 */
export function instanceOfJSONB(value: object): value is JSONB {
    return true;
}

export function JSONBFromJSON(json: any): JSONB {
    return JSONBFromJSONTyped(json, false);
}

export function JSONBFromJSONTyped(json: any, ignoreDiscriminator: boolean): JSONB {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function JSONBToJSON(json: any): JSONB {
    return JSONBToJSONTyped(json, false);
}

export function JSONBToJSONTyped(value?: JSONB | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

