/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeUnit } from './KnowledgeUnit';
import {
    KnowledgeUnitFromJSON,
    KnowledgeUnitFromJSONTyped,
    KnowledgeUnitToJSON,
    KnowledgeUnitToJSONTyped,
} from './KnowledgeUnit';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
    DocumentToJSONTyped,
} from './Document';

/**
 * 
 * @export
 * @interface KnowledgeUnitWithDocumentsResponse
 */
export interface KnowledgeUnitWithDocumentsResponse {
    /**
     * 
     * @type {KnowledgeUnit}
     * @memberof KnowledgeUnitWithDocumentsResponse
     */
    knowledgeUnit?: KnowledgeUnit;
    /**
     * 
     * @type {Array<Document>}
     * @memberof KnowledgeUnitWithDocumentsResponse
     */
    documents?: Array<Document>;
}

/**
 * Check if a given object implements the KnowledgeUnitWithDocumentsResponse interface.
 */
export function instanceOfKnowledgeUnitWithDocumentsResponse(value: object): value is KnowledgeUnitWithDocumentsResponse {
    return true;
}

export function KnowledgeUnitWithDocumentsResponseFromJSON(json: any): KnowledgeUnitWithDocumentsResponse {
    return KnowledgeUnitWithDocumentsResponseFromJSONTyped(json, false);
}

export function KnowledgeUnitWithDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeUnitWithDocumentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'knowledgeUnit': json['knowledgeUnit'] == null ? undefined : KnowledgeUnitFromJSON(json['knowledgeUnit']),
        'documents': json['documents'] == null ? undefined : ((json['documents'] as Array<any>).map(DocumentFromJSON)),
    };
}

export function KnowledgeUnitWithDocumentsResponseToJSON(json: any): KnowledgeUnitWithDocumentsResponse {
    return KnowledgeUnitWithDocumentsResponseToJSONTyped(json, false);
}

export function KnowledgeUnitWithDocumentsResponseToJSONTyped(value?: KnowledgeUnitWithDocumentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'knowledgeUnit': KnowledgeUnitToJSON(value['knowledgeUnit']),
        'documents': value['documents'] == null ? undefined : ((value['documents'] as Array<any>).map(DocumentToJSON)),
    };
}

