/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentRequest } from './DocumentRequest';
import {
    DocumentRequestFromJSON,
    DocumentRequestFromJSONTyped,
    DocumentRequestToJSON,
    DocumentRequestToJSONTyped,
} from './DocumentRequest';

/**
 * 
 * @export
 * @interface KnowledgeUnitRequest
 */
export interface KnowledgeUnitRequest {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeUnitRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeUnitRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<DocumentRequest>}
     * @memberof KnowledgeUnitRequest
     */
    documents?: Array<DocumentRequest>;
    /**
     * 
     * @type {Array<DocumentRequest>}
     * @memberof KnowledgeUnitRequest
     */
    newDocuments?: Array<DocumentRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof KnowledgeUnitRequest
     */
    addedDocumentsIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof KnowledgeUnitRequest
     */
    removedDocumentsIds?: Array<string>;
}

/**
 * Check if a given object implements the KnowledgeUnitRequest interface.
 */
export function instanceOfKnowledgeUnitRequest(value: object): value is KnowledgeUnitRequest {
    return true;
}

export function KnowledgeUnitRequestFromJSON(json: any): KnowledgeUnitRequest {
    return KnowledgeUnitRequestFromJSONTyped(json, false);
}

export function KnowledgeUnitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeUnitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'documents': json['documents'] == null ? undefined : ((json['documents'] as Array<any>).map(DocumentRequestFromJSON)),
        'newDocuments': json['newDocuments'] == null ? undefined : ((json['newDocuments'] as Array<any>).map(DocumentRequestFromJSON)),
        'addedDocumentsIds': json['addedDocumentsIds'] == null ? undefined : json['addedDocumentsIds'],
        'removedDocumentsIds': json['removedDocumentsIds'] == null ? undefined : json['removedDocumentsIds'],
    };
}

export function KnowledgeUnitRequestToJSON(json: any): KnowledgeUnitRequest {
    return KnowledgeUnitRequestToJSONTyped(json, false);
}

export function KnowledgeUnitRequestToJSONTyped(value?: KnowledgeUnitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'documents': value['documents'] == null ? undefined : ((value['documents'] as Array<any>).map(DocumentRequestToJSON)),
        'newDocuments': value['newDocuments'] == null ? undefined : ((value['newDocuments'] as Array<any>).map(DocumentRequestToJSON)),
        'addedDocumentsIds': value['addedDocumentsIds'],
        'removedDocumentsIds': value['removedDocumentsIds'],
    };
}

