/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KnowledgeUnitResourceWithDocumentGroupsResponse } from './KnowledgeUnitResourceWithDocumentGroupsResponse';
import {
    KnowledgeUnitResourceWithDocumentGroupsResponseFromJSON,
    KnowledgeUnitResourceWithDocumentGroupsResponseFromJSONTyped,
    KnowledgeUnitResourceWithDocumentGroupsResponseToJSON,
    KnowledgeUnitResourceWithDocumentGroupsResponseToJSONTyped,
} from './KnowledgeUnitResourceWithDocumentGroupsResponse';
import type { KnowledgeUnit } from './KnowledgeUnit';
import {
    KnowledgeUnitFromJSON,
    KnowledgeUnitFromJSONTyped,
    KnowledgeUnitToJSON,
    KnowledgeUnitToJSONTyped,
} from './KnowledgeUnit';

/**
 * 
 * @export
 * @interface KnowledgeUnitWithResourcesResponse
 */
export interface KnowledgeUnitWithResourcesResponse {
    /**
     * 
     * @type {KnowledgeUnit}
     * @memberof KnowledgeUnitWithResourcesResponse
     */
    knowledgeUnit?: KnowledgeUnit;
    /**
     * 
     * @type {Array<KnowledgeUnitResourceWithDocumentGroupsResponse>}
     * @memberof KnowledgeUnitWithResourcesResponse
     */
    resources?: Array<KnowledgeUnitResourceWithDocumentGroupsResponse>;
}

/**
 * Check if a given object implements the KnowledgeUnitWithResourcesResponse interface.
 */
export function instanceOfKnowledgeUnitWithResourcesResponse(value: object): value is KnowledgeUnitWithResourcesResponse {
    return true;
}

export function KnowledgeUnitWithResourcesResponseFromJSON(json: any): KnowledgeUnitWithResourcesResponse {
    return KnowledgeUnitWithResourcesResponseFromJSONTyped(json, false);
}

export function KnowledgeUnitWithResourcesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeUnitWithResourcesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'knowledgeUnit': json['knowledgeUnit'] == null ? undefined : KnowledgeUnitFromJSON(json['knowledgeUnit']),
        'resources': json['resources'] == null ? undefined : ((json['resources'] as Array<any>).map(KnowledgeUnitResourceWithDocumentGroupsResponseFromJSON)),
    };
}

export function KnowledgeUnitWithResourcesResponseToJSON(json: any): KnowledgeUnitWithResourcesResponse {
    return KnowledgeUnitWithResourcesResponseToJSONTyped(json, false);
}

export function KnowledgeUnitWithResourcesResponseToJSONTyped(value?: KnowledgeUnitWithResourcesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'knowledgeUnit': KnowledgeUnitToJSON(value['knowledgeUnit']),
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(KnowledgeUnitResourceWithDocumentGroupsResponseToJSON)),
    };
}

