/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Manager API
 * The Knowledge Manager API provides endpoints for managing knowledge units. A knowledge unit aggregates multi-dimensional information needed for specific tasks, enabling cross-domain information reuse and contextual knowledge assembly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentGroup } from './DocumentGroup';
import {
    DocumentGroupFromJSON,
    DocumentGroupFromJSONTyped,
    DocumentGroupToJSON,
    DocumentGroupToJSONTyped,
} from './DocumentGroup';
import type { KnowledgeUnitResource } from './KnowledgeUnitResource';
import {
    KnowledgeUnitResourceFromJSON,
    KnowledgeUnitResourceFromJSONTyped,
    KnowledgeUnitResourceToJSON,
    KnowledgeUnitResourceToJSONTyped,
} from './KnowledgeUnitResource';

/**
 * 
 * @export
 * @interface KnowledgeUnitResourceWithDocumentGroupsResponse
 */
export interface KnowledgeUnitResourceWithDocumentGroupsResponse {
    /**
     * 
     * @type {KnowledgeUnitResource}
     * @memberof KnowledgeUnitResourceWithDocumentGroupsResponse
     */
    knowledgeUnitResource?: KnowledgeUnitResource;
    /**
     * 
     * @type {Array<DocumentGroup>}
     * @memberof KnowledgeUnitResourceWithDocumentGroupsResponse
     */
    documentGroups?: Array<DocumentGroup>;
}

/**
 * Check if a given object implements the KnowledgeUnitResourceWithDocumentGroupsResponse interface.
 */
export function instanceOfKnowledgeUnitResourceWithDocumentGroupsResponse(value: object): value is KnowledgeUnitResourceWithDocumentGroupsResponse {
    return true;
}

export function KnowledgeUnitResourceWithDocumentGroupsResponseFromJSON(json: any): KnowledgeUnitResourceWithDocumentGroupsResponse {
    return KnowledgeUnitResourceWithDocumentGroupsResponseFromJSONTyped(json, false);
}

export function KnowledgeUnitResourceWithDocumentGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeUnitResourceWithDocumentGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'knowledgeUnitResource': json['knowledgeUnitResource'] == null ? undefined : KnowledgeUnitResourceFromJSON(json['knowledgeUnitResource']),
        'documentGroups': json['documentGroups'] == null ? undefined : ((json['documentGroups'] as Array<any>).map(DocumentGroupFromJSON)),
    };
}

export function KnowledgeUnitResourceWithDocumentGroupsResponseToJSON(json: any): KnowledgeUnitResourceWithDocumentGroupsResponse {
    return KnowledgeUnitResourceWithDocumentGroupsResponseToJSONTyped(json, false);
}

export function KnowledgeUnitResourceWithDocumentGroupsResponseToJSONTyped(value?: KnowledgeUnitResourceWithDocumentGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'knowledgeUnitResource': KnowledgeUnitResourceToJSON(value['knowledgeUnitResource']),
        'documentGroups': value['documentGroups'] == null ? undefined : ((value['documentGroups'] as Array<any>).map(DocumentGroupToJSON)),
    };
}

